name: PHP Tests

on: [push]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: php-actions/composer@v5

      - name: PHPUnit Tests
        uses: php-actions/phpunit@v2
        env:
          TEST_NAME: Friday
        with:
          bootstrap: vendor/autoload.php
          configuration: ./phpunit.xml
          args: --colors --testdox
